In [ ]:
import numpy as np
zeros_arr=np.zeros(5)
print(zeros_arr)
print(type(zeros_arr))
zeros_arr.dtype
zeros_arr.astype(np.int32)



[0. 0. 0. 0. 0.]
<class 'numpy.ndarray'>


array([0, 0, 0, 0, 0], dtype=int32)

In [55]:
arr=np.array([[1,4,6],[5,6,7],[8,9,5],[3,5,6]])
print(arr)
print(np.swapaxes(arr,1,0))
print("Shape of the array:",arr.shape)
print("datatype of array:",arr.dtype)
print(np.swapaxes(arr,1,0))
print(np.max(arr))

[[1 4 6]
 [5 6 7]
 [8 9 5]
 [3 5 6]]
[[1 5 8 3]
 [4 6 9 5]
 [6 7 5 6]]
Shape of the array: (4, 3)
datatype of array: int64
[[1 5 8 3]
 [4 6 9 5]
 [6 7 5 6]]
9


In [54]:
arr=np.array([[1,4,6],[5,6,7],[8,9,5],[3,5,6]])
print(arr.reshape(3,4))

[[1 4 6 5]
 [6 7 8 9]
 [5 3 5 6]]


In [53]:
arr=np.array([[1,4,6],[5,6,7],[8,9,5],[3,5,6]])
print(np.linspace(1,5,num=5))#use to get perticular range value

[1. 2. 3. 4. 5.]


In [52]:
ones_arr=np.ones(5,dtype="int")
print(ones_arr)


[1 1 1 1 1]


In [48]:
arr=np.array([[1,4,6],[5,6,7],[8,9,5],[3,5,6]])
print(np.sort(arr,axis=0))
print(np.sort(arr,axis=1))

[[1 4 5]
 [3 5 6]
 [5 6 6]
 [8 9 7]]
[[1 4 6]
 [5 6 7]
 [5 8 9]
 [3 5 6]]


In [24]:
arr=np.array([[1,2,3],[4,5,6],[6,7,8]])
print(arr)
print(arr.shape)
print(arr.dtype)

[[1 2 3]
 [4 5 6]
 [6 7 8]]
(3, 3)
int64
