In [ ]:
import numpy as np
zeros_arr=np.zeros(5)
print(zeros_arr)
print(type(zeros_arr))
zeros_arr.dtype
zeros_arr.astype(np.int32)



[0. 0. 0. 0. 0.]
<class 'numpy.ndarray'>


array([0, 0, 0, 0, 0], dtype=int32)

In [55]:
arr=np.array([[1,4,6],[5,6,7],[8,9,5],[3,5,6]])
print(arr)
print(np.swapaxes(arr,1,0))
print("Shape of the array:",arr.shape)
print("datatype of array:",arr.dtype)
print(np.swapaxes(arr,1,0))
print(np.max(arr))

[[1 4 6]
 [5 6 7]
 [8 9 5]
 [3 5 6]]
[[1 5 8 3]
 [4 6 9 5]
 [6 7 5 6]]
Shape of the array: (4, 3)
datatype of array: int64
[[1 5 8 3]
 [4 6 9 5]
 [6 7 5 6]]
9


In [54]:
arr=np.array([[1,4,6],[5,6,7],[8,9,5],[3,5,6]])
print(arr.reshape(3,4))

[[1 4 6 5]
 [6 7 8 9]
 [5 3 5 6]]


In [53]:
arr=np.array([[1,4,6],[5,6,7],[8,9,5],[3,5,6]])
print(np.linspace(1,5,num=5))#use to get perticular range value

[1. 2. 3. 4. 5.]


In [52]:
ones_arr=np.ones(5,dtype="int")
print(ones_arr)


[1 1 1 1 1]


In [48]:
arr=np.array([[1,4,6],[5,6,7],[8,9,5],[3,5,6]])
print(np.sort(arr,axis=0))
print(np.sort(arr,axis=1))

[[1 4 5]
 [3 5 6]
 [5 6 6]
 [8 9 7]]
[[1 4 6]
 [5 6 7]
 [5 8 9]
 [3 5 6]]


In [ ]:
arr=np.array([[1,2,3],[4,5,6],[6,7,8]])
print(arr)
# print(arr.shape)
# print(arr.dtype)
# print(arr.ndim)
# print(arr.size)
# print(arr.shape)
# print(arr[-1])
arr.argmax
arr.argmin #differnt attribute,arr dispalya 1 2 3 ,rearange,reshape,

[[1 2 3]
 [4 5 6]
 [6 7 8]]
(3, 3)
int64
2
9
(3, 3)
[6 7 8]


In [ ]:
import numpy as np
array1=np.arange(2,11) # it arrange the element
# array1
b=array1.reshape(3,3) #it reshape the 
b


array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [ ]:
?arr #docstring  it tells how our function can do

Type:        ndarray
String form:
[[1 2 3]
 [4 5 6]
 [6 7 8]]
Length:      3
File:        c:\users\sai\appdata\roaming\python\python312\site-packages\numpy\__init__.py
Docstring:  
ndarray(shape, dtype=float, buffer=None, offset=0,
        strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an array.

For more information, refer to the `numpy` module and examine the
methods and attributes of an array.

Parameters
----------
(for the __new__ method; see Notes below)

shape : tuple of ints
    Shape of created array.
dtype : data

In [39]:
import numpy as np
array2=np.array([1,2,3,4,5,6,7,8]) #1D array
print("1D array")
print(array2)
print("----------------------------")
array3=np.array([[1,2,3],[4,5,6],[7,8,9,]]) #2D array
print("2D array")
print(array3)
print("----------------------------")
array4=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[2,4,6]]]) #3D array
print("3D array")
print(array4)


1D array
[1 2 3 4 5 6 7 8]
----------------------------
2D array
[[1 2 3]
 [4 5 6]
 [7 8 9]]
----------------------------
3D array
[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [2 4 6]]]


In [23]:
# Array indexing
print(array2)
print(array2[1])
print(array2[5])
print(array2[-1])
print(array2[-3])



[1 2 3 4 5 6 7 8]
2
6
8
6


In [42]:
#Array Attribute
print(array4)
print("------------------------")
print(array2)
print("------------------------")
print(array3)
print("------------------------")
print(array3.shape) #it shows the shape of the array in the terms of rows and column 
print(array2.size)  #it shows the count of array element
print(array3.dtype) # it shows the data type of element
print(array4.ndim) #it shows the dimentions like 1d,2d,3d
print(array4.nbytes) #it shows bytes of array



[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [2 4 6]]]
------------------------
[1 2 3 4 5 6 7 8]
------------------------
[[1 2 3]
 [4 5 6]
 [7 8 9]]
------------------------
(3, 3)
8
int64
3
96


In [ ]:
array1=np.arange(2,11) # it arrange the element 
print(array1)


array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
b=array1.reshape(3,3) #it reshape the array in the form of rows and column
print(b)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [49]:
#arithmatic operations
arr1=np.array([2,4,5,6,7,8])
arr2=np.array([1,2,3,4,6,7])
add=arr1+arr2
print(add) #it gives addition of two array
sub=arr1-arr2
print(sub) #it gives sub
mul=arr1*arr2
print(mul) # it gives mul
div=arr1/arr2
print(div)
mod=arr1%arr2
print(mod)

[ 3  6  8 10 13 15]
[1 2 2 2 1 1]
[ 2  8 15 24 42 56]
[2.         2.         1.66666667 1.5        1.16666667 1.14285714]
[0 0 2 2 1 1]


In [ ]:
# self learning 
print(arr2)
print(np.argmax(arr2)) #it gives the max num index
print(np.argmin(arr2)) #it gives the min value index
print(np.linspace(0,2,num=6)) #it gives the number between range ,the specific number count which we declare as num=6
print(np.diff(arr2)) #it shows the difference between the  each elements 

[1 2 3 4 6 7]
5
0
5
[0.  0.4 0.8 1.2 1.6 2. ]
[1 1 1 2 1]
